In [63]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/cuiyang/Desktop/project2.csv')
df

,vehicle type,detectiontime_o,gantryid_o,detectiontime_d,gantryid_d,triplength,tripend,info
0,31,2019/8/30 8:17,03F3307N,2019/8/30 8:17,03F3307N,5.2,Y,2019-08-30 08:17:14+03F3307N
1,31,2019/8/30 8:01,03F0648S,2019/8/30 8:01,03F0648S,5.6,Y,2019-08-30 08:01:02+03F0648S
2,31,2019/8/30 8:51,03F0648N,2019/8/30 8:57,03F0559N,13.9,Y,2019-08-30 08:51:45+03F0648N; 2019-08-30 08:57...
3,31,2019/8/30 8:20,03F3854S,2019/8/30 8:20,03F3854S,8.6,Y,2019-08-30 08:20:45+03F3854S
4,32,2019/8/30 8:06,03F4168S,2019/8/30 8:09,03F4232S,9.3,Y,2019-08-30 08:06:10+03F4168S; 2019-08-30 08:09...
...,...,...,...,...,...,...,...,...
259618,31,2019/8/30 8:50,01F0376N,2019/8/30 8:53,01F0339N,8.4,Y,2019-08-30 08:50:21+01F0376N; 2019-08-30 08:53...
259619,31,2019/8/30 8:07,01F0248S,2019/8/30 8:34,01F0681S,46.0,Y,2019-08-30 08:07:35+01F0248S; 2019-08-30 08:08...
259620,31,2019/8/30 8:19,05F0309N,2019/8/30 8:19,05F0309N,8.3,Y,2019-08-30 08:19:05+05F0309N
259621,31,2019/8/30 8:38,05F0055N,2019/8/30 8:38,05F0055N,10.7,Y,2019-08-30 08:38:11+05F0055N
259622,32,2019/8/30 8:42,03F0150N,2019/8/30 8:42,03F0150N,3.6,Y,2019-08-30 08:42:35+03F0150N

In [34]:
# types = df['vehicle type'].tolist()
# df1 = pd.DataFrame(index=['vehicle type','detectiontime_o','gantryid_o','detectiontime_d','gantryid_d','triplength','tripend','info'])
# df2 = pd.DataFrame(columns=['vehicle type','detectiontime_o','gantryid_o','detectiontime_d','gantryid_d','triplength','tripend','info'])
# df3 = pd.DataFrame(columns=['vehicle type','detectiontime_o','gantryid_o','detectiontime_d','gantryid_d','triplength','tripend','info'])
# df4 = pd.DataFrame(columns=['vehicle type','detectiontime_o','gantryid_o','detectiontime_d','gantryid_d','triplength','tripend','info'])
# df5 = pd.DataFrame(columns=['vehicle type','detectiontime_o','gantryid_o','detectiontime_d','gantryid_d','triplength','tripend','info'])

# for i in range(len(df)):
#     if types[i] == 5:
#         df1 = df1.append(df.iloc[i,:])
#     elif types[i] == 31:
#         df2 = df2.append(df.iloc[i,:])
#     elif types[i] == 32:
#         df3 = df3.append(df.iloc[i,:])
#     elif types[i] == 41:
#         df4 = df4.append(df.iloc[i,:])
#     elif types[i] == 42:
#         df5 = df5.append(df.iloc[i,:])
        

# def SearchCall():
#     type_info = e_user.get()
#     trip_info = e_user1.get()
# #     print(info)
#     if type_info in types:
#         for i in range(len(df)):
#             if types[i] == type_info:
#                 df1.append(df.iloc[i,:])
#     return df1

In [59]:

def SearchCall():    ## 需修改
    type_info = e_user.get()
    trip_info = e_user1.get()
    print(type_info)
    print(trip_info)
    
    
def dtime():
    df1 = df.sort_values(by='detectiontime_o')
    return df1

def atime():
    df2 = df.sort_values(by='detectiontime_d')
    print(df2)

def triplen():
    df3 = df.sort_values(by='triplength')
    print(df3)
    
def gantryo():
    df4 = df.sort_values(by='gantryid_o')
    print(df4)
    
def gantryd():
    df5 = df.sort_values(by='gantryid_d')
    print(df5)

In [67]:
import tkinter as tk    

root = tk.Tk()    
root.title('5051 project2')    
root.geometry('600x600')


def check1():
    if v_type.get() == True:     
        e_user.configure(state = tk.NORMAL)
    else:
        e_user.configure(state = tk.DISABLED)
        
def check2():
    if trip.get() == True:     
        e_user1.configure(state = tk.NORMAL)
    else:
        e_user1.configure(state = tk.DISABLED)

def check3():
    if gantido.get() == True:     
        e_user2.configure(state = tk.NORMAL)
    else:
        e_user2.configure(state = tk.DISABLED)

        
        
## Search part       
w = tk.Label(root, text="Search", font=("华文行楷", 20), fg="blue")
w.pack()
 

# 1.vehicle type
v_type = tk.BooleanVar()
c1 = tk.Checkbutton(root, text='Vehicle Type', variable=v_type,command=check1)
c1.pack()
# input of the type
e_user =tk.Entry(root, state=tk.DISABLED)
e_user.pack()


# 2.trip length
trip= tk.BooleanVar()
c2 = tk.Checkbutton(root, text='Trip Length', variable=trip,command=check2)
c2.pack()
# input of the trip length
e_user1 =tk.Entry(root, state=tk.DISABLED)
e_user1.pack()


# 2.gantryid_o
gantido= tk.BooleanVar()
c3 = tk.Checkbutton(root, text='GantryID O', variable=gantido,command=check3)
c3.pack()
# input of the id
e_user2 =tk.Entry(root, state=tk.DISABLED)
e_user2.pack()



search_btn = tk.Button(root,text = 'Search',bg = 'red', command = SearchCall)
search_btn.pack()


## Sort part
w1 = tk.Label(root, text="Sort", font=("华文行楷", 20), fg="blue")
w1.pack()
 

dtime_sort = tk.Button(root,text = 'Departure Time',bg = 'red', command = dtime)
dtime_sort.pack()

atime_sort = tk.Button(root,text = 'Arrive Time',bg = 'red', command = atime)
atime_sort.pack()

length_sort = tk.Button(root,text = 'Trip Length',bg = 'red', command = triplen)
length_sort.pack()

ganto_sort = tk.Button(root,text = 'GantryID O',bg = 'red', command = gantryo)
ganto_sort.pack()

gantd_sort = tk.Button(root,text = 'GantryID D',bg = 'red', command = gantryd)
gantd_sort.pack()


root.mainloop()